# Generated by Django 2.2.24 on 2024-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240808_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
    ]
