# Generated by Django 2.2.24 on 2024-08-08 19:20

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats_set = Flat.objects.all()
    if not flats_set.exists():
        return None
    for flat in flats_set.iterator():
        owner_created, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            defaults={
                'full_name': flat.owner,
                'pure_phone': flat.owner_pure_phone,
                'phonenumber': flat.owners_phonenumber,
            }
        )
        owner_created.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20240808_2220'),
    ]

    operations = [
        migrations.RunPython(fill_owners),
    ]
